/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 laptop.gltf --transform
Author: edouard77 (https://sketchfab.com/edouard77)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-d7459b8ceaab4ce09230cee0b85b5e4b
Title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-4.33, 79.14, -0.24]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group position={[0.02, 7.31, 0.33]}>
          <mesh geometry={nodes.Laptop_Screen_Material002_0.geometry} material={materials['Black_Keys.001']} />
          <mesh geometry={nodes.Laptop_Screen_Black_Keys_0.geometry} material={materials.Black_Keys} />
          <mesh geometry={nodes.Laptop_Screen_Ecran_0.geometry} material={materials.Ecran} />
        </group>
        <mesh geometry={nodes.Laptop_Keyboard_Black_Keys002_0.geometry} material={materials['Black_Keys.002']} />
        <mesh geometry={nodes.Laptop_Keyboard_Black_Keys_0.geometry} material={materials.Black_Keys} />
        <mesh geometry={nodes.Laptop_Keyboard_Black_Keys001_0.geometry} material={materials['Black_Keys.001']} />
        <mesh geometry={nodes.Laptop_Keyboard_side_slot_0.geometry} material={materials.side_slot} />
        <mesh geometry={nodes.Laptop_Keyboard_Black_Plastic_ROUGH_0.geometry} material={materials.Black_Plastic_ROUGH} />
      </group>
    </group>
  )
}

useGLTF.preload('/laptop-transformed.glb')
