/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 white-plaster-3d-model.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/white-plaster-3d-model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sphere_gltf.geometry} material={materials.white_plaster_02} color="purple" />
    </group>
  )
}

useGLTF.preload('/white-plaster-3d-model-transformed.glb')
